body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }

        .quiz-container {
            width: 70%;
            margin: auto;
        }

        .board-title {
            font-size: 1.5em;
            font-weight: bold;
            margin-bottom: 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .quiz-card {
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 15px;
            margin-bottom: 15px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .quiz-header {
            font-size: 1.2em;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .quiz-meta {
            color: #555;
            font-size: 0.8em;
            margin-bottom: 10px;
        }

        .quiz-title{
            font-size: 1.3em;
            font-weight: bold;
            padding-left: 10px;
        }

        .quiz-info {
            margin-left: 10px;
        }

        .answer{
            font-size: 1.3em;
            font-weight: bold;
            text-align: center;
        }

        .category-link {
            font-size: 1em;
            color: #555;
            text-decoration: none;
            margin-bottom: 10px;
            display: block;
        }
        
        .button-container {
            overflow: hidden;
        }

        .logout-button {
            float: left;
        }

        .write-button {
            float: right;
        }

        .button-container div {
            width: 50%;
            box-sizing: border-box;
        }